name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"

      - run: pnpm install --prefer-frozen-lockfile
      - run: pnpm run check && pnpm run build