name: Renovate
permissions:
  pull-requests: write
on:
  workflow_dispatch:
  schedule:
    - cron: "* */12 * * *"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Run renovate
        uses: renovatebot/github-action@v40.2.10
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
